title: Shany Ben-David
keywords: [
  "Shany Ben-David", 
  "Shany Ben David", 
  "Eylon Yogev", 
  "Omer Paneth",
  "Gal Arnon",
  "Yael Tauman Kalai",
  "Bar-Ilan University", 
  "Cryptography", 
  "Theoretical Computer Science", 
  "Interactive Proofs", 
  "Fiat-Shamir",
  "PCP", 
  "Private Information Retrieval", 
  "Verifiable PIR", 
  "Zero-Knowledge"
]
description: The academic homepage of Shany Ben-David, Ph.D. student in Computer Science
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap